# Generated by Django 5.1.7 on 2025-03-28 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0002_alter_usuarioscustomizados_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetos',
            name='ordem',
            field=models.IntegerField(db_index=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projetos',
            name='descricaoBackEnd',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projetos',
            name='descricaoFrontEnd',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projetos',
            name='descricaoLonga',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projetos',
            name='linkCodigoFonte',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='projetos',
            name='linkDeploy',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='projetos',
            name='linkVideoDemonstracao',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
