# Generated by Django 5.1.7 on 2025-03-28 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0003_projetos_ordem_alter_projetos_descricaobackend_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetos',
            name='ordem',
            field=models.IntegerField(db_index=True, unique=True),
        ),
    ]
