# Generated by Django 5.1.7 on 2025-03-28 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0004_alter_projetos_ordem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projetos',
            old_name='linkCodigoFonte',
            new_name='linkRepositorio',
        ),
    ]
