# Generated by Django 5.1.7 on 2025-03-28 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0005_rename_linkcodigofonte_projetos_linkrepositorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetos',
            name='stacksString',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
