# Generated by Django 5.1.7 on 2025-03-28 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0006_projetos_stacksstring'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projetos',
            name='stacksString',
        ),
        migrations.AlterField(
            model_name='projetos',
            name='stacks',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
