# Generated by Django 5.1.7 on 2025-03-28 19:54

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0007_remove_projetos_stacksstring_alter_projetos_stacks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetos',
            name='descricaoBackEnd',
            field=markdownx.models.MarkdownxField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='projetos',
            name='descricaoFrontEnd',
            field=markdownx.models.MarkdownxField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='projetos',
            name='descricaoLonga',
            field=markdownx.models.MarkdownxField(max_length=600),
        ),
    ]
