# Generated by Django 5.1.7 on 2025-03-31 16:22

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0010_alter_projetos_descricaolonga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetos',
            name='descricaoLonga',
            field=markdownx.models.MarkdownxField(blank=True, max_length=600, null=True),
        ),
    ]
