# Generated by Django 5.1.7 on 2025-03-31 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0011_alter_projetos_descricaolonga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetos',
            name='descricaoLonga',
            field=models.TextField(blank=True, null=True),
        ),
    ]
