# Generated by Django 5.1.7 on 2025-03-31 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0012_alter_projetos_descricaolonga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetos',
            name='descricaoBackEnd',
            field=models.TextField(blank=True, help_text='Use Markdown para formatação', null=True),
        ),
        migrations.AlterField(
            model_name='projetos',
            name='descricaoFrontEnd',
            field=models.TextField(blank=True, help_text='Use Markdown para formatação', null=True),
        ),
        migrations.AlterField(
            model_name='projetos',
            name='descricaoLonga',
            field=models.TextField(blank=True, help_text='Use Markdown para formatação', null=True),
        ),
    ]
