# Generated by Django 5.1.7 on 2025-03-31 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0013_alter_projetos_descricaobackend_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetos',
            name='descricaoBackEnd',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projetos',
            name='descricaoFrontEnd',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projetos',
            name='descricaoLonga',
            field=models.TextField(blank=True, null=True),
        ),
    ]
