# Generated by Django 5.1.7 on 2025-03-31 20:51

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0014_alter_projetos_descricaobackend_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetos',
            name='descricaoBackEnd',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projetos',
            name='descricaoFrontEnd',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projetos',
            name='descricaoLonga',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
    ]
