# Generated by Django 5.1.7 on 2025-03-31 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0015_alter_projetos_descricaobackend_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projetos',
            name='descricaoBackEnd',
        ),
        migrations.RemoveField(
            model_name='projetos',
            name='descricaoFrontEnd',
        ),
        migrations.RemoveField(
            model_name='projetos',
            name='descricaoLonga',
        ),
        migrations.AddField(
            model_name='projetos',
            name='descricoes',
            field=models.FileField(blank=True, null=True, upload_to='descricoes/'),
        ),
    ]
